name: NegXus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  slide_to_act: ^2.0.2
  get: ^4.6.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.svg
    - assets/icons/conn_icon.svg
    - assets/icons/socket.svg
    - assets/icons/emoji.svg
    - assets/icons/gallery.svg
    - assets/icons/mic.svg
    - assets/icons/send.svg
    - assets/icons/status_icon.svg
    - assets/Images/boy_png.png
    - assets/Images/girl_png.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
