name: NegXus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  slide_to_act: ^2.0.2
  get: ^4.6.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  uuid: ^4.2.2
  zego_uikit: ^2.27.16
  zego_uikit_signaling_plugin: ^2.8.6
  zego_uikit_prebuilt_live_streaming: ^3.13.5
  http: ^1.0.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  zego_uikit_prebuilt_call: ^4.16.28
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.svg
    - assets/icons/conn_icon.svg
    - assets/icons/socket.svg
    - assets/icons/emoji.svg
    - assets/icons/gallery.svg
    - assets/icons/mic.svg
    - assets/icons/send.svg
    - assets/icons/status_icon.svg
    - assets/icons/call.svg
    - assets/icons/delete.svg
    - assets/icons/security.svg
    - assets/icons/user.svg
    - assets/Images/boy_png.png
    - assets/Images/girl_png.png
    - assets/icons/videocall.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/Fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/Fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
